### ISSUE TITLE
Do we need detect firstly in wizards whether application installed?

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/hawk#134]
For example,
I want to configure MySQL/MariaDB in wizards,
I input id and required params, leaving "install" option with “No”,
and then I click "Verify", no errors happen, and then "Apply", wizards told me "successfully",

But I got the failed status because I never installed the application.
The process can make me feel wasting time.

If we detect whether application installed firstly when user enter the specific wizards page,
if the application not installed, with "install" option "No", nothing can continue.
that's better process:)

Regards,
xin

**Comment by ayoub-belarbi** [comment]
I completely agree with you, but since there is an intention to change the wizards to be managed by Salt instead of the crmsh's cluster-scripts, we can adopt a simpler solution for now and show a permanent message in the top of the page (at least in the first step of each wizard) saying that you should install the application in question beforehand.

Thanks,

**Comment by ayoub-belarbi** [comment]
Closing this issue!
