### ISSUE TITLE
Fedora 31 support ?

### ISSUE THREAD

**Issue by averyfreeman** [ClusterLabs/hawk#184]
Thanks for the project, it looks really promising

However, upstream development in several spaces that would benefit from clustering is dominated by RedHat - most notably Ceph and KVM/Libvirt - which makes it kind of puzzling why you'd be so closely aligned with OpenSUSE (?)

Is there some modifications I could make to the Makefile that would ease building on a RedHat-styled OS?  I'm using Fedora 31 server.

Thanks :)

**Comment by diegoakechi** [comment]
Hi @averyfreeman,

Originally, the so-called `Linux HA` and today called `Clusterlabs` project was created by SUSE being `Hawk`, `crmsh` and even `pacemaker`, components that formed the solution stack. At a certain point in time, Red Hat has decided to follow a different direction and has created `PCS`, that is the equivalent of `crmsh` and `Hawk` on their distribution.

Hawk is not promising, but already in use by many users for many years.

If you want to contribute to making it work on Fedora or any Red Hat-styled distribution, your contributions will be well accepted.

Regards,

**Comment by averyfreeman** [comment]
Hello,

Thank you for clarifying the distinction. Because of the divergent paths, will hawk ever be a viable option on a pcs environment, or is it's dependency on crmsh a deal breaker?

I would like to help make hawk multi-platform but am not really sure where to start. In my Fedora build environment I was getting lots of errors from Ruby re: rake, even though rake is installed (error: ruby2.5/rake is not a valid interpreter message - when I'm using Ruby 2.6 and rake is present)

Can you give a programming noob like me an idea of how to resolve this?

thanks

**Comment by diegoakechi** [comment]
Hi,

Hawk is dependent of crmsh, so it would need to be available on Fedora too. AFAIR some colleagues have been maintaining crmsh for CentOS since a long time, so shouldn't be a big deal to build it for Fedora.

About the error you see, it is must probably because you are using the RPM package built for SUSE and it depends on Ruby2.5, but Hawk is a standard Ruby on Rails application, so I think the first thing you would need to do is to adjust the RPM package to the Ruby packaging policies on Fedora, so the Ruby on Rails can properly find the Ruby binaries.

**Comment by averyfreeman** [comment]
OK great I will see what I can do. I'm guessing that's the .spec file but if that's not it I'll dig around until I find a reference to ruby 2.5.  Thank you :)
