### ISSUE TITLE
Redhat package

### ISSUE THREAD

**Issue by phemmer** [ClusterLabs/hawk#72]
The documentation says you can just run `make rpm` to build a package for Fedora based systems. This does not appear to be the case, as it does not work on EL7 (specifically CentOS/7).

I was able to build an RPM spec file by hand and get this up and running. But I had to do a lot of really crude things in the spec file to get it working.

Additionally I've implemented a few patches to the source to resolve some issues. I would submit these as pull requests, but I'm not sure if any of them are due to the horrible spec file I had to write. If we can an get official RPM spec for EL, and the issues are still present, I'll create the PRs.

**Comment by ayoub-belarbi** [comment]
Thanks @phemmer for your input! The fact that the documentation mentions that `make rpm` is enough to build the package for Fedora based systems is due to the fact that it hasn't been updated since a while. The project is very promising and we intend to build new features that will dramatically improve Hawk but we lack of contributions for the moment especially for maintaining the application on Fedora and Debian based systems and your help will be a great thing!
